language: swift
xcode_project: ThunderRequest.xcodeproj # path to your xcodeproj folder
osx_image: xcode11
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderRequest-iOS
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max
    - xcode_scheme: ThunderRequest-macOS
      xcode_destination: platform=macOS
    - xcode_scheme: ThunderRequest-tvOS
      xcode_destination: platform=tvOS Simulator,OS=13.0,name=Apple TV 4K
