language: swift
xcode_project: ThunderRequest.xcodeproj # path to your xcodeproj folder
xcode_scheme: ThunderRequest
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="ThunderRequest-iOS"
  - TVOS_FRAMEWORK_SCHEME="ThunderRequest-tvOS"
  - OSX_FRAMEWORK_SCHEME="ThunderRequest-macOS"
  - IOS_SDK=iphonesimulator12.2
  - TVOS_SDK=appletvsimulator12.2
  - OSX_SDK=macosx10.14
  matrix:
    include:
      - xcode_scheme: "$IOS_FRAMEWORK_SCHEME"
        xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XS Max
      - xcode_scheme: "$OSX_FRAMEWORK_SCHEME"
        xcode_destination: platform=macOS
      - xcode_scheme: "$TVOS_FRAMEWORK_SCHEME"
        xcode_destination: platform=tvOS Simulator,OS=12.2,name=Apple TV 4K

    # - DESTINATION="OS=11.0.1,name=iPhone 5s"        SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.0.1,name=iPhone 8 Plus"    SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.1,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.2,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.1,name=iPhone 8 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.2,name=iPhone 8 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.0,name=iPhone 8 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.0,name=iPhone X"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.1,name=iPhone XR"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.1,name=iPhone XS Max"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.2,name=iPhone XÊ€"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=12.2,name=iPhone XS Max"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
    # - DESTINATION="OS=11.0,name=Apple TV 4K"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    # - DESTINATION="OS=11.1,name=Apple TV 4K"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    # - DESTINATION="OS=11.2,name=Apple TV 4K"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    # - DESTINATION="OS=12.0,name=Apple TV 4K"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    # - DESTINATION="OS=12.1,name=Apple TV 4K"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    # - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
